# Generated by Django 4.1.1 on 2022-09-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['descripcion', 'id'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['nombre'], 'verbose_name': 'Productos', 'verbose_name_plural': 'Productos'},
        ),
    ]
