# Generated by Django 4.1.1 on 2022-09-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0006_postulante_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulante',
            old_name='apellido',
            new_name='apellidos',
        ),
    ]
