# Generated by Django 4.1.1 on 2022-09-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0007_rename_apellido_postulante_apellidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ('nombre',), 'verbose_name': 'Empresa'},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='telefonos',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='email',
            new_name='correo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ruc',
        ),
    ]
